version: '3'
services:
  app:
    build: .
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    ports:
      - ${TRACKSTATUS_APP_PORT}:5000
    volumes:
      - .:/myapp
    depends_on:
      - postgres

  postgres:
    # This expects that the username and password are set outside the codebase in POSTGRES_USER and POSTGRES_PASSWORD
    env_file: .env
    ports:
      - 5432:5432      
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    image: postgres
    
  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - ./rundata/redis:/data

  sidekiq:
    build: .
    env_file: .env
    command: ./entrypoint_sidekiq.sh
    volumes:
      - .:/myapp
